---
jobs:
  hadolint: #https://github.com/marketplace/actions/yamllint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: hadolint/hadolint-action@v1.6.0
      with:
        failure-threshold: style
  yamllint: #https://github.com/marketplace/actions/yamllint-github-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: karancode/yamllint-github-action@v2.0.0

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: github/super-linter/slim@v4
        env:
          ERROR_ON_MISSING_EXEC_BIT: 'true'
          VALIDATE_ALL_CODEBASE: 'true'
          YAML_ERROR_ON_WARNING: 'true'
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build
      uses: docker/build-push-action@v2
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        platforms: linux/amd64
        push: false
name: Test
on:
  push:
    branches-ignore:
    - main
  pull_request:
    branches:
    - main
