---
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: github/super-linter/slim@v4
        env:
          ERROR_ON_MISSING_EXEC_BIT: 'true'
          VALIDATE_ALL_CODEBASE: 'false'
          YAML_ERROR_ON_WARNING: 'false'
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build
      uses: docker/build-push-action@v2
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        platforms: linux/amd64
        push: false
name: Test
on:
  push:
    branches-ignore:
    - main
  pull_request:
    branches:
    - main
