#!/usr/bin/with-contenv bash

export SAMBA_SHARE=${SAMBA_SHARE:-data}
export USERNAME=${USERNAME:-admin}
export PUID=${PUID:-1000}
export PGID=${PGID:-1000}

confd -onetime -backend env || exit 1

cat /etc/samba/smb.conf
