#!/usr/bin/with-contenv bash

export PUID=${PUID:-1000}
export PGID=${PGID:-1000}

mkdir -p /data || exit 1

find /data ! -group ${PGID} -exec chown -c ${PUID}.${PGID} {} \; || exit 1
find /data ! -user ${PUID} -exec chown -c ${PUID} {} \; || exit 1

find /data -type d ! -perm 0755 -exec chmod -c 0755 {} \; || exit 1
find /data -type f ! -perm 0644 -exec chmod -c 0644 {} \; || exit 1
